name: Deploy Alfonso Ugarte Web

on:
  push:
    branches:
      - main # Asegúrate que sea el nombre de tu rama principal

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Setup Node.js ⚙️
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install Dependencies 🔧
        run: npm install --legacy-peer-deps

      - name: Build Project 🏗️
        run: npm run build -- --base-href /portal-ullulluco/ 
        # Importante: Reemplaza NOMBRE_DE_TU_REPO por el nombre real de tu proyecto en GitHub

      - name: Deploy to GitHub Pages 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist/alfonso-ugarte-ullulluco/browser # Reemplaza NOMBRE_DE_PROYECTO por el que sale en tu carpeta dist
          branch: gh-pages # Rama donde se guardará la web publicada